name: Startup Alchemy
favicon: null
layout_spectrum: 0.4983
typography_spectrum: 0.75043
title: 'Secrets of innovation & entrepreneurship'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.049580876249819994
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.9828767706640065
purpose: []
